server:
  port: 8084

spring:
  application:
    name: work-queue-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        concurrency: 2  # 最小消费者数量
        max-concurrency: 5  # 最大消费者数量
        prefetch: 1  # 启用公平分

logging:
  level:
    root: INFO
