server:
  port: 8081

spring:
  application:
    name: simple-queue-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /

logging:
  level:
    root: INFO