server:
  port: 8082

spring:
  application:
    name: simple-queue-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /

logging:
  level:
    root: INFO
